---

- name: Clone packer repo
  ansible.builtin.git:
    repo: https://github.com/wbthomason/packer.nvim
    dest: "{{ ansible_env.HOME }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
    depth: 1
  tags:
    - neovim

- name: ensures nvim dirs exsist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim/lua"
    state: directory
  tags:
    - neovim

- name: Copy init.lua
  ansible.builtin.copy:
    src: init.lua
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.lua"
  tags:
    - neovim

- name: Copy plugins.lua
  ansible.builtin.copy:
    src: plugins.lua
    dest: "{{ ansible_env.HOME }}/.config/nvim/lua/plugins.lua"
  tags:
    - neovim

- name: ensures nvim/after dir exsist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim/after"
    state: directory
  tags:
    - neovim

- name: Synchronize plugin files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/nvim/after/plugin/"
  with_fileglob:
      - "plugins/*"
  tags:
    - neovim

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: plugins.lua
    dest: "{{ ansible_env.HOME }}/.config/nvim/lua/plugins.lua"
  tags:
    - neovim

- name: ensures nvim spell dir exsist
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/nvim/spell"
    state: directory
  tags:
    - neovim

- name: Synchronize custome dictionary
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/nvim/spell/"
  with_fileglob:
      - "spell/*"
  tags:
    - neovim
