---

- name: Do Arch OS Specific Stuff
  when:
    - ansible_facts['os_family'] == 'Archlinux'
  ansible.builtin.debug:
    msg: "Performing Archlinux Specific Configuration"

- name: Has escalated privileges
  ansible.builtin.debug:
    msg: Has escalated privileges {{ has_escalated_privileges }}

- name: Pacman upgrade all packages
  when:
    - has_escalated_privileges == True
  become: yes
  community.general.pacman:
    update_cache: true
    upgrade: true
  tags:
    - arch_linux

- name: Pacman install common packages for Archlinux
  when:
    - has_escalated_privileges == True
  become: yes
  community.general.pacman:
    name:
      - base-devel
      - flatpak
      - git
      - less
      - linux-headers
      - ncdu
      - neovim
      - ntfs-3g
      - openssh
      - pacman-contrib
      - partitionmanager
      - poetry
      - pyenv
      - ripgrep
      - tmux
      - tree
#      - update-alternatives
      - vagrant
      - yay
      - zsh
    state: present
