---

- name: Pacman install common packages for Archlinux
  when:
    - has_escalated_privileges == True
  become: yes
  community.general.pacman:
    name:
      # KDE - Desktop Environment
      - alacritty
      - bluedevil
      - bluez
      - bluez-utils
      - chromium
      - code
      - dolphin
      - gparted
      - grsync
      - kcalc
      - obsidian
      - plasma-meta
      - power-profiles-daemon
      - sddm
      - terminator
      - transmission-qt
    state: present

#- name: Install yay packages
#  community.general.yay:
#    name:
#      - kopia
#      - plasma-ksmserver
#      - virtualbox
#      - virtualbox-host-dkms
#      - virtualbox-host-modules-arch
#    state: present


- name: Start KDE Power Management
  ansible.builtin.systemd_service:
    name: power-profiles-daemon
    enabled: true
    state: started

- name: Start KDE Bluetooth Service
  ansible.builtin.systemd_service:
    name: bluetooth
    enabled: true
    state: started
